---
- name: Register with RHN
  redhat_subscription:
    state: present
    username: "{{ redhat.user }}"
    password: "{{ redhat.pass }}"

- name: attach to pool
  command: subscription-manager attach --pool={{ rhosp_pool }}

- name: add OSP repositories
  command: subscription-manager repos --enable={{ item }}
  with_items: "{{ rhosp_repos }}"
